name: ESLint

on:
  - push
  - pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: hallee/eslint-action@1.0.3 
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
